[workspace]
resolver = "2"
members = [
	"can-socket",
	"canopen-tokio",
	"canopen-tokio/examples"
]

[patch.crates-io]
trybuild = { git = "https://github.com/de-vri-es/trybuild", branch = "full-build" }
